### DISCUSSION TITLE
Getting cuda error running speedrun.sh on H100:8

### DISCUSSION THREAD

**Discussion by ggilley** [karpathy/nanochat#272] [General]
Want to do my own run. Using lambda.ai. H100:8

git clone from 20 minutes ago.

ran speedrun.sh. Getting cuda error Any ideas:
```

Step 00000 | Validation bpb: 3.3013
[rank4]: Traceback (most recent call last):
[rank4]:   File "/home/ubuntu/.local/share/uv/python/cpython-3.10.19-linux-x86_64-gnu/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank4]:     return _run_code(code, main_globals, None,
[rank4]:   File "/home/ubuntu/.local/share/uv/python/cpython-3.10.19-linux-x86_64-gnu/lib/python3.10/runpy.py", line 86, in _run_code
[rank4]:     exec(code, run_globals)
[rank4]:   File "/home/ubuntu/test/nanochat/scripts/base_train.py", line 272, in <module>
[rank4]:     loss.backward()
[rank4]:   File "/home/ubuntu/test/nanochat/.venv/lib/python3.10/site-packages/torch/_tensor.py", line 625, in backward
[rank4]:     torch.autograd.backward(
[rank4]:   File "/home/ubuntu/test/nanochat/.venv/lib/python3.10/site-packages/torch/autograd/__init__.py", line 354, in backward
[rank4]:     _engine_run_backward(
[rank4]:   File "/home/ubuntu/test/nanochat/.venv/lib/python3.10/site-packages/torch/autograd/graph.py", line 841, in _engine_run_backward
[rank4]:     return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
[rank4]:   File "/home/ubuntu/test/nanochat/.venv/lib/python3.10/site-packages/torch/autograd/function.py", line 315, in apply
[rank4]:     return user_fn(self, *args)
[rank4]:   File "/home/ubuntu/test/nanochat/.venv/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 2303, in backward
[rank4]:     return impl_fn()
[rank4]:   File "/home/ubuntu/test/nanochat/.venv/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 2289, in impl_fn
[rank4]:     out = CompiledFunction._backward_impl(ctx, all_args)
[rank4]:   File "/home/ubuntu/test/nanochat/.venv/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 2461, in _backward_impl
[rank4]:     out = call_func_at_runtime_with_args(
[rank4]:   File "/home/ubuntu/test/nanochat/.venv/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/utils.py", line 129, in call_func_at_runtime_with_args
[rank4]:     out = normalize_as_list(f(args))
[rank4]:   File "/home/ubuntu/test/nanochat/.venv/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 1044, in _fn
[rank4]:     return fn(*args, **kwargs)
[rank4]:   File "/home/ubuntu/test/nanochat/.venv/lib/python3.10/site-packages/torch/_inductor/output_code.py", line 613, in __call__
[rank4]:     return self.current_callable(inputs)
[rank4]:   File "/home/ubuntu/test/nanochat/.venv/lib/python3.10/site-packages/torch/_inductor/utils.py", line 2962, in run
[rank4]:     out = model(new_inputs)
[rank4]:   File "/tmp/torchinductor_ubuntu/cb/ccb5wlsdgewxlenl7cq6o5rkzsnxpwf2hd4e254txllsfnifhca3.py", line 1679, in call
[rank4]:     triton_red_fused__log_softmax__log_softmax_backward_data__to_copy__unsafe_view_div_mul_nll_loss_backward_nll_loss_forward_tanh_tanh_backward_view_0.run(buf2, primals_125, tangents_1, convert_element_type_568, amax, log, 65536, 65536, stream=stream4)
[rank4]:   File "/home/ubuntu/test/nanochat/.venv/lib/python3.10/site-packages/torch/_inductor/runtime/triton_heuristics.py", line 1272, in run
[rank4]:     self.autotune_to_one_config(*args, **kwargs)
[rank4]:   File "/home/ubuntu/test/nanochat/.venv/lib/python3.10/site-packages/torch/_inductor/runtime/triton_heuristics.py", line 1048, in autotune_to_one_config
[rank4]:     timings = self.benchmark_all_configs(*args, **kwargs)
[rank4]:   File "/home/ubuntu/test/nanochat/.venv/lib/python3.10/site-packages/torch/_inductor/runtime/triton_heuristics.py", line 1022, in benchmark_all_configs
[rank4]:     timings = {
[rank4]:   File "/home/ubuntu/test/nanochat/.venv/lib/python3.10/site-packages/torch/_inductor/runtime/triton_heuristics.py", line 1023, in <dictcomp>
[rank4]:     launcher: self.bench(launcher, *args, **kwargs)
[rank4]:   File "/home/ubuntu/test/nanochat/.venv/lib/python3.10/site-packages/torch/_inductor/runtime/triton_heuristics.py", line 853, in bench
[rank4]:     cpu_copies = self.copy_args_to_cpu_if_needed(*args, **kwargs)
[rank4]:   File "/home/ubuntu/test/nanochat/.venv/lib/python3.10/site-packages/torch/_inductor/runtime/triton_heuristics.py", line 934, in copy_args_to_cpu_if_needed
[rank4]:     maybe_copy(name, arg)
[rank4]:   File "/home/ubuntu/test/nanochat/.venv/lib/python3.10/site-packages/torch/_inductor/runtime/triton_heuristics.py", line 918, in maybe_copy
[rank4]:     cpu_arg = torch.empty_strided(
[rank4]: torch.AcceleratorError: CUDA error: invalid argument
[rank4]: Search for `cudaErrorInvalidValue' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html for more information.
[rank4]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
```

**Comment by ggilley** [comment]
I thought maybe it was pytorch 2.9. I changed pyproject.toml to

`    "torch>=2.8.0,<2.9",`

But it still fails in the same way. 🤷

**Comment by svlandeg** [comment]
Hi @ggilley, that's odd. Can you see any installation issues in the log on the console? Can you share the full output of `pip list`?

**Comment by ggilley** [comment]
There weren't any installation issues that I could see. I tore down the instance. I'll try again if it will help with debugging. Anything else I can capture?

**Comment by svlandeg** [comment]
@ggilley: there are some vibe-coded PRs (https://github.com/karpathy/nanochat/pull/259 and https://github.com/karpathy/nanochat/pull/270) that suggest setting some environment variables. You could try whether any of that works for you. If it does, it would be super helpful if you'd print out the values of those env vars before executing any code, just to double check whether maybe any of those are different in your setup than for other users. 

It might still be that those PRs include a solution / explanation to your issues. But we'd need someone to actually reproduce and test (and not just vibe code a potential solution that may or may not address the problem).

**Comment by ggilley** [comment]
So I tried it today straight from the repo and it worked 🤷 

Must have been a full moon.

**Reply by svlandeg** [reply]
Happy to hear it's working now, thanks for reporting back! 🙏
